apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: kn-connectors
  labels:
    eventing.knative.dev/connector: log-sink
    eventing.knative.dev/broker: default
  name: kn-connector-log-sink
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: kn-connector-log-sink
    uri: /events
